apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 58.2.2
    helm:
      releaseName: monitoring
      values: |
        grafana:
          adminPassword: "prom-operator"
          
          additionalDataSources:
            - name: Prometheus
              type: prometheus
              uid: prometheus
              url: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
              access: proxy
              isDefault: true
              jsonData:
                httpMethod: POST

          envValueFrom:
            TG_BOT_TOKEN:
              secretKeyRef:
                name: tg-secret
                key: bottoken
            TG_CHAT_ID:
              secretKeyRef:
                name: tg-secret
                key: chatid

          alerting:
            contactpoints.yaml:
              apiVersion: 1
              contactPoints:
                - orgId: 1
                  name: Telegram
                  receivers:
                    - uid: tg_bot
                      type: telegram
                      settings:
                        bottoken: "${TG_BOT_TOKEN}"
                        chatid: "${TG_CHAT_ID}"
                        message: '{{ template "custom_tg_alert" . }}'
                        parseMode: "HTML"
            policies.yaml:
              apiVersion: 1
              policies:
                - orgId: 1
                  receiver: Telegram
                  group_by: ['alertname', 'namespace']
                  group_wait: 10s
                  group_interval: 1m
                  repeat_interval: 10m
            templates.yaml:
              apiVersion: 1
              templates:
                - orgId: 1
                  name: custom_tg_alert
                  template: |
                    {{ define "custom_tg_alert" }}
                    {{ range .Alerts }}
                    {{ if eq .Status "firing" }}🚨 <b>ALERT: FIRING!</b> 🚨{{ else }}✅ <b>ALERT: RESOLVED!</b> ✅{{ end }}
                    <b>Alert:</b> {{ .Labels.alertname }}
                    <b>App:</b> {{ .Labels.deployment }}
                    <b>Namespace:</b> {{ .Labels.namespace }}
                    {{ end }}
                    {{ end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
