apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud' # Переконайся, що лінк правильний
    targetRevision: HEAD
    path: k8s-infrastructure/apps/nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/nodejs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/flask
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/postgres
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/cloudflared
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/pihole
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/minio
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/vaultwarden
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/uptime-kuma
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batpepe/devops-homelab-k3s-hybrid-cloud'
    targetRevision: HEAD
    path: k8s-infrastructure/apps/homepage
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
