apiVersion: apps/v1
kind: Deployment
metadata:
  name: batman-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batman
  template:
    metadata:
      labels:
        app: batman
    spec:
      containers:
      - name: batman
        image: ghcr.io/batpepe/batman-app:c398987d32713de87c3f5dc9578618d53a98f2bd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: batman-svc
  namespace: apps
spec:
  selector:
    app: batman
  ports:
  - port: 80
    targetPort: 80
