apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: ghcr.io/batpepe/nodejs-app:735c30ff9f1cbc7b2eda45b6c3179899f9916f1e
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  namespace: apps
spec:
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app  # Має збігатися з labels у твоєму Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
spec:
  rules:
  - host: nodejs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-service
            port:
              number: 80
