name: Build Batman Game

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/batman-app/**'
      - '.github/workflows/ci-batman.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: batpepe/batman-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: ./apps/batman-app
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Update K8s manifest
        run: |
          sed -i -E "s|image: ghcr.io/batpepe/batman-app:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" k8s-infrastructure/apps/nginx/batman.yaml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add k8s-infrastructure/apps/nginx/batman.yaml
          git commit -m "gitops: update batman-app image to ${{ github.sha }}" || echo "No changes"
          git pull --rebase origin main
          git push
