name: Build Node.js App

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/nodejs-app/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: batpepe/nodejs-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./apps/nodejs-app
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Update K8s manifest
        run: |
          sed -i -E "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s-infrastructure/apps/nginx/nginx-app.yaml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add k8s-infrastructure/apps/nginx/nginx-app.yaml
          git commit -m "gitops: update nginx-app image to ${{ github.sha }}" || echo "No changes"
          git pull --rebase origin main  # <-- Ось магічний рядок, який рятує від Race Condition
          git push
