name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/flask-app/**' # Запускати тільки якщо змінився код аппки

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: batpepe/flask-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Дозвіл на запис у сховище образів

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/flask-app
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
